### ISSUE TITLE
Consider joining forces with Coconut?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [radix/sumtypes#3]
[Coconut](http://coconut-lang.org/) is an extension of Python (every valid Python program is valid Coconut) that adds partial application, pattern matching, static typing, lazy lists, and  other useful things. It aspires to offer immuitable algebraic data types, but [seems to](https://gitter.im/evhub/coconut?at=5a3891321a4e6c822327127e) have [no support](https://github.com/evhub/coconut/issues/418) for sum types.

**Comment by radix** [comment]
I mean, I guess you can use this library in a coconut program, but I assume they would want built-in language level support.
